package ifneeded app-ghost 1.0 [list source [file join $dir ghost.tcl]]
package ifneeded app-util 1.0 [list source [file join $dir util.tcl]]
package ifneeded app-gui 1.0 [list source [file join $dir gui.tcl]]
package ifneeded app-proxy 1.0 [list source [file join $dir proxy.tcl]]
package ifneeded app-update 1.0 [list source [file join $dir update.tcl]]
